### ISSUE TITLE
[REQ] Automatic Chore Claim Approval

### ISSUE THREAD

**Issue by ccpk1** [ad-ha/kidschores-ha#18]
### Is your feature request related to a problem?

- [ ] Yes

### Please describe the problem

There may be some chores that a parent is willing to trust the kid to do without requiring approval and it could be fairly straightforward feature to implement in the future.

### Describe the solution you'd like

I think the easiest way might be to add an option on each chore with a checkbox for "Automatic claim approval."  If that attribute was stored in the sensor for the chore it would be possible easily trigger once the chore went into claimed status.

Option 1 - When the kid clicks the button to claim, have the system look for the attribute before exiting... if the attribute is found, have the system run it through the approve handling.  (Of course it would have to have a bypass for the user checking that prevents kids from approving)

Option 2 - Create the attribute in the chore as described, but point the user to some yaml or a blueprint that could be used in an automation.  See automation in alternatives below.

### Describe alternatives you've considered

The user could also create their own automation where they create triggers as all of the sensors for the chores they want to automate approvals for, then use some templating to "press" the associated button for the chore claimed.  This would be easy to do, it would just mean the user needs to take an additional step to go modify their automation when they create a new chore they want automated rather than have it dynamic with the chore.  Below is a simple automation I made to confirm the concept works.

```
automation:
  alias: Testing Automatic Approval
  description: ""
  triggers:
    - trigger: state
      entity_id:
        - sensor.kaden_status_brush_teeth_morning
      to: claimed
  conditions: []
  actions:
    - action: button.press
      metadata: {}
      data: {}
      target:
        entity_id: button.kaden_approve_chore_brush_teeth_morning
  mode: single
```
